### ISSUE TITLE
Storage not found in MIUI 13 / Android 12

### ISSUE THREAD

**Issue by JordiGP1** [butzist/ActivityLauncher#109]
com.android.settings.Settings$StorageDashboardActivity not found in MIUI 13 / Android 12

**Comment by butzist** [comment]
This is with version 1.13.5 on Android 11 (LineageOS):

![Screenshot_20220105-063356_Activity_Launcher](https://user-images.githubusercontent.com/2405792/148165753-950027ef-802f-4fc5-bc75-1a79a655e781.png)

Which app version are you using? Have you tried using the Search bar?

**Comment by JordiGP1** [comment]
I'm using version 1.13.5 on Android 12, with MIUI 13.
In Android 11 with MIUI 12.5 works ok.

The link apears, but not works ok, it's a black screen... (Sorry for my english...,i put a picture) 

![Screenshot_2022-01-05-07-51-54-859_com miui securitycenter](https://user-images.githubusercontent.com/97140910/148173525-e29aafa1-9c86-4730-ae19-5a4d3294352e.jpg)
![Screenshot_2022-01-05-07-50-24-103_de szalkowski activitylauncher](https://user-images.githubusercontent.com/97140910/148173542-ff2ebdb9-e262-4af2-817a-fbf4580e6e0e.jpg)
![Screenshot_2022-01-05-07-50-32-106_com android settings](https://user-images.githubusercontent.com/97140910/148173548-562eeb7a-421f-400d-890d-1ff3d865e87a.jpg)

**Comment by drogga** [comment]
@JordiGP1 - Not Activity Launcher's fault, we can't do anything about this, blame MIUI instead.
_(I will appreciate if power advanced users, that actually want to do stuff on their devices stop buying Chinese devices with crippled Firmware / ROM as all of those that have their own name for their forks of android and because of them people keep unnecessary writing pointless issues and give bad rating...)_

**Comment by butzist** [comment]
@JordiGP1 Is you device rooted?
I'm not aware of any change in launching of activities - sure it's not due to an update in the settings app?

**Comment by JordiGP1** [comment]
No, my device is not rooted. I'm in weekly miui 13 on poco f3/ redmi k40.

**Comment by butzist** [comment]
Did you try with other apps that can start activities, ie https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker ?

**Comment by JordiGP1** [comment]
Yes, I did.

And not found. Do the same error.

**Comment by butzist** [comment]
Then I'm not sure how we could get it working - probably rather an issue with miui, right?

**Comment by butzist** [comment]
Maybe someone with miui can try to play with the ActivityLauncher code and see if there is a way for starting this activity

**Comment by Vasilisxiros** [comment]
Same problem
![Screenshot_2022-01-07-10-42-01-216_de szalkowski activitylauncher](https://user-images.githubusercontent.com/97313685/148639984-64201d03-210f-4833-94be-b8a0ab1d05b2.jpg)

**Comment by butzist** [comment]
You cannot start unexported activities without admin privileges (ie rooted phone)

**Comment by drogga** [comment]
@Vasilisxiros You are probably trying to launch some of the private and unexported activities, those have a blue lock icon on them and require root in order to be launched, please do some reading, instead of writing pointless complains.
Can a other similar app that can list activities launch this exact activity - probably not, so why do you think that Activity Launcher can magically launch it ?, it can't do miracles !

Also, please, when you show an example in a form of a screenshot or whatever, at least make sure to be in English (can be achieved by setting the Android display language to ENg).

**Comment by AbhiTheModder** [comment]
@drogga and @butzist  sir you're right that those with blue tick require root/admin privileges
But there are other also which without blue tick but they also can't be opened.

I know the reason also as an reverse engineer I seen all the components of this app it's definitely awesome coded 🔥 and reason behind not opening those are that your app detects hidden launch activity of apps also and those which only opens in back to help another activities to run and Simply Android can't define them to run that's why shows Java error messages 

Thanks 😊

**Comment by Vasyan41** [comment]
Здравствуйте, проблема с miui13 Android 12 совсем не показывает в папке архив что бы произвести действие очистки кеша. На андроид 11 проблем не испытывал.

**Comment by AbhiTheModder** [comment]
Не могли бы вы поделиться несколькими скриншотами, которые будут более информативнымиFrom: Vasyan41Sent: 12 March 2022 01:00 PMTo: butzist/ActivityLauncherCc: AbhiTheModder; CommentSubject: Re: [butzist/ActivityLauncher] Storage not found in MIUI 13 / Android 12 (Issue #109) Здравствуйте, проблема с miui13 Android 12 совсем не показывает в папке архив что бы произвести действие очистки кеша. На андроид 11 проблем не испытывал.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>
