### ISSUE TITLE
Support for Android TV

### ISSUE THREAD

**Issue by the4anoni** [butzist/ActivityLauncher#131]
Hi
Like in topic. Activity launcher doesn't show up as app on my android tv box (Canal+ Box 4k) stock launcher, to run it I need Sideload launcher or LeanbackOnFire. Also google play doesn't let me download it on my tv box.
![screen](https://user-images.githubusercontent.com/13403084/150833343-286e81e7-fcd7-4236-98a7-46209df2e19f.png)

App works fine, with workarounds mentioned above, and sideloading it manually, but it would be much more comfortable to update app via google play store. Better font for TV usage would be nice too ;)

**Comment by Ismael034** [comment]
Hi @the4anoni 
The reason you are not able to install the app via Play Store is that the it has not been design to work with Android TV. Android TV requires an additional review to validate [TV App Quality](https://developer.android.com/docs/quality-guidelines/tv-app-quality). 

We might add support for Android TV soon as I dont think it will require a lot of changes. Also feel free to create a Pull request addressing this issue.

Thanks!

**Comment by darkj2k** [comment]
I second this. There are lots hidden activities on  Android TV from different TV brands. Activity Launcher is so useful for this situation. Even Android TV can't support activities creation right now, I can still use it to find out and launch these activities. Making it support Android TV officially will be great. Support activities creation on Android TV will be even great. Maybe like TV App Repo to save these activities as apk?  [https://www.apkmirror.com/apk/felker-tech/tv-app-repo-android-tv/tv-app-repo-android-tv-1-1-4-playstore-release/tv-app-repo-android-tv-1-1-4-playstore-android-apk-download/](url)

**Comment by drogga** [comment]
@darkj2k
Making it appear in the leanback launcher with a banner is easy, I can probably do this right now if I had time, but fully supporting a navigation with a remote arrows in order to click menu buttons is another thing...
Leanback doesn't support shortcuts creation and it probably never will...
Compiling a companion (shortcut) app, just to launch another app is not the way, so I don't see a point in implementing this, simply as this app is intended to be mainly used with touchscreens (or mouse), like on phones and tablets and not on TVs, there you can launch some activities, but that's all.

**Comment by Ismael034** [comment]
Hi,
So the main issue with adding support for Android tv is getting it uploaded to the play store as it would require a complete redesign, add remote functionality, etc... which is a ton of work.

For now, we can enable the launcher icon so it wouldn't be necessary to use a third party launcher to launch the app. Sideloading would be still be necessary to install/update the app.

**Comment by butzist** [comment]
Merged - will have to check in Play Dev console how to enable listing for TV.
