### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by JajulaUdaySai** [butzist/ActivityLauncher#150]
Getting error while accessing App Lock 

![Screenshot_20220330-093330_Activity Launcher](https://user-images.githubusercontent.com/37185777/160749309-cfab9ee2-18b5-46fd-961d-bee852c1c125.jpg)

**Comment by JajulaUdaySai** [comment]
@drogga , is the fix going to come in next update? If yes can you please let me know expected update days because I have masked and locked many important apps, which I am not able to unmask and remove lock

**Comment by JajulaUdaySai** [comment]
@drogga , is the fix going to come in next update? If yes can you please let me know expected update days because I have masked and locked many important apps, which I am not able to unmask and remove lock

**Comment by drogga** [comment]
@JajulaUdaySai
Those activities are private (there's a icon on them), that's why you get that toast msg., they are not meant to be launched that way and you shouldn't poke things you don't understand, A.L. is not for "anybody", nor you should hold anyone responsible for the mistakes you make with it, or expect someone to "debug" your device, that's why there's a disclaimer message when you launch the app for a first time !

I closed this and your other (same) issue, simply because it's not Activity Launcher's fault and we cannot help you, so no need to discuss this any further and I won't be replying regarding this anymore (I might even also start locking the pointless issue tickets).

If you want to get the things how they were, you probably should consider performing a factory (hard) reset, tho this doesn't guarantee that everything will be back as it was if you updated your software / firmware in the meantime, because lately newer app and OS vers., mostly break things, instead of fixing them (blame Google and Samsung)...

Please don't open another issue regarding this.
Thank you.

**Comment by drogga** [comment]
@JajulaUdaySai
Those activities are private (there's a padlock icon on them), that's why you get that toast msg., they are not meant to be launched that way and you shouldn't poke things you don't understand, A.L. is not for "anybody", nor you should hold anyone responsible for the mistakes you make with it, or expect someone to "debug" your device, that's why there's a disclaimer message when you launch the app for a first time !

I closed this and your other (same) issue, simply because it's not Activity Launcher's fault and we cannot help you, so no need to discuss this any further and I won't be replying regarding this anymore (I might even also start locking the pointless issue tickets).

If you want to get the things how they were, you probably should consider performing a factory (hard) reset, tho this doesn't guarantee that everything will be back as it was if you updated your software / firmware in the meantime, because lately newer app and OS vers. mostly break things, instead of fixing them (blame Google and Samsung)...

Please don't open another issue regarding this.
Thank you.
