### ISSUE TITLE
Error with ru-rUA language

### ISSUE THREAD

**Issue by DrimTim2020** [butzist/ActivityLauncher#162]
And so I ran into a problem, first of all, reading the changes, I see that the ru-rUA language has been added!
But after installation, the program turned out to be in English.
I started digging and wanted to translate it already)), but as it turned out, after unpacking your program, I saw this is what I will indicate on the screen.
It turned out that the ru-rRU folder was not deleted and it contained a file with the English language .
![IMG_20220707_130354](https://user-images.githubusercontent.com/65110869/177750044-e880d114-035f-4ac5-b31a-2ca9946e9178.jpg)
And so my actions, I deleted the folder ( ru-rRU ) and packed it back into a file and installed it, the whole program was installed as it should be and was in Russian.

**Comment by drogga** [comment]
@butzist ^

**Comment by butzist** [comment]
Translations should be updates via Crowdin

**Comment by DrimTim2020** [comment]
> ```
It is not updated and does not work.
Read carefully what I described to begin with, and not what you are saying.

```

**Comment by DrimTim2020** [comment]
> Translations should be updates via Crowdin

It is not updated and does not work.
Read carefully what I described to begin with, and not what you are saying.

**Comment by DrimTim2020** [comment]
> Translations should be updates via Crowdin

@butzist 
1) Russian-Ukrainian language is not in the program to select it.

https://user-images.githubusercontent.com/65110869/186890475-d58e4b34-b537-4992-bae6-e16435869e06.mp4

2) Delete the folder from the ru-rRU program, it contains the strings.txt file in English

**Comment by drogga** [comment]
Indeed, here in the source (a bit different from what you see in the APK Editor) the "values-ru-rRU" contains only ENg strings, but that's basically the same with many others, where they are either partially translated (2-3 string lines, like values-bg-rBG), or fully in English, my opinion is that those should be removed and only added when and if they are fully translated, else they are pointless and only add to the file size and build time, which both can be reduced if they are removed.
The same partially applies to the /descriptions, even tho those are not build/being included in the .apk file.

@DrimTim2020 Are you using the latest Actions workflow build, or one from the Releases page ?, because those are outdated there and haven't been updated any time soon.

@butzist Would you please check ?, something seems off...

**Comment by DrimTim2020** [comment]
> @DrimTim2020 Are you using the latest Actions workflow build, or one from the Releases page ?, because those are outdated there and haven't been updated any time soon.

I'm using the latest version from the Play store ( Activity launcher 1.14.4 ).
Everything that I described above in this post, after this procedure, the Russian-Ukrainian language is pulled up automatically from the ru-rUA folder, although it is not in the manual selection list.

**Comment by drogga** [comment]
I'm not sure that the PS versions are that up to date, also ignore the versionName and versionCode as those are not necessarily being updated with every beta build (you can consider those as beta builds), I've DLed and installed the latest "Actions" build from couple of hours ago and there might not be a Russian, but there is "Украïнська (Украïна)" in the list of languages to select, in your video too, third one from bottom to top. Also, it doesn't get clear which of the 2 languages you want the app to actually display to, is the UKR actually RU and what's the difference between those 2 - IDK, because I don't make a difference between them, since I don't know them, both are gibberish to me.
Anyway, in order to fully apply any of the languages, the app should be restarted (cleared from the recents list).

**Comment by DrimTim2020** [comment]
> I'm not sure that the PS versions are that up to date, also ignore the versionName and versionCode as those are not necessarily being updated with every beta build (you can consider those as beta builds), I've DLed and installed the latest "Actions" build from couple of hours ago and there might not be a Russian, but there is "Украïнська (Украïна)" in the list of languages to select, in your video too, third one from bottom to top. Also, it doesn't get clear which of the 2 languages you want the app to actually display to, is the UKR actually RU and what's the difference between those 2 - IDK, because I don't make a difference between them, since I don't know them, both are gibberish to me. Anyway, in order to fully apply any of the languages, the app should be restarted (cleared from the recents list).

I live in Ukraine and for me the language is both Ukrainian and Russian.
I own them equally.
But the preferred language is Russian .
The author indicated that he removed the Russian ru-rRU , but he did not delete the folder from the apk file and now the ru-rRU folder conflicts with the ru-rUA folder, and since the ru-rRU folder contains the strings.txt file in English, the ru-rUA language is not used in the system because of this.
But he added ru-rUA, which is the same Russian language, but with an indication that it is of Ukrainian origin.

**Comment by drogga** [comment]
The Russian lang. was removed and then added back, but since you claim that UKR is actually RU, instead of deleting the "values-ru-rRU" folder (that actually contains EN strings), the the "strings.xml" should be moved from "values-ru-rUA" to "values-ru-rRU", but there's also "values-uk-rUA", which confuses me even more and it's a mess with those 3 it seems.

Probably the "System Default" option is a bit broken and doesn't actually pick the system's Display or Region languages, or maybe not correctly in order to show/display the app in that lang. on first launch.

**Comment by DrimTim2020** [comment]
> The Russian lang. was removed and then added back, but since you claim that UKR is actually RU, instead of deleting the "values-ru-rRU" folder (that actually contains EN strings), the the "strings.xml" should be moved from "values-ru-rUA" to "values-ru-rRU", but there's also "values-uk-rUA", which confuses me even more and it's a mess with those 3 it seems.
> 
> Probably the "System Default" option is a bit broken and doesn't actually pick the system's Display or Region languages, or maybe not correctly in order to show/display the app in that lang. on first launch.

You don’t understand, because you are probably Balgarin or your language is Balgar. so for me Balgar is gibberish)).
But everything is clear to me, and the place to be ru-rUA is the correct name of the folder, it should be so.
And the uk-rUA folder is a purely Ukrainian language and it also has a place to be.

**Comment by drogga** [comment]
This lang. I pointed only as an example, because I clicked on to check out the strings, since is one of the lowest translation progress percentage, also you didn't wrote it correctly (both times), for me personally everything is in English and any extra lang. is pointless that only adds extra complexity (/bulk) and everything besides English is pointless, as everyone should know it and all programs for whatever OS or platform should be in it, but that's a personal opinion, which I'm not trying to force to anyone.

You wrote:
"But he added ru-rUA, which is the same Russian language, but with an indication that it is of Ukrainian origin."
Which means that the place of this strings.xml file is actually wrong and should be moved, but since I'm not 100% sure, I'm not going to do anything, even tho I can (in case you haven't seen my badge, go look it on Desktop, since it's only shown there).

**Comment by DrimTim2020** [comment]
> This lang. I pointed only as an example, because I clicked on to check out the strings, since is one of thelowest translation progress percentage, also you didn't wrote it correctly (both times), for me personally everything is in English and any extra lang. is pointless that only adds extra complexity (/bulk) and everything besides English is pointless, as everyone should know it and all programs for whatever OS or platform should be in it, but that's a personal opinion, which I'm not trying to force to anyone.
> 
> You wrote: "But he added ru-rUA, which is the same Russian language, but with an indication that it is of Ukrainian origin." Which means that the place of this strings.xml file is actually wrong and should be moved, but since I'm not 100% sure, I'm not going to do anything, even tho I can (in case you haven't seen my badge, go look it on Desktop, since it's only shown there).

Your presentation is absolutely wrong.
There is room for other languages.
And they don't take up that much space. 6 kilobytes of a translation file in your opinion takes up a lot of space. you are a joke though.
Maybe we're talking about different things?
Let's stop this?
I've never been wrong, everything I said was true.
You speak differently, so stop this balabolism over trifles.

**Comment by drogga** [comment]
"I've never been wrong, everything I said was true."
:D, there's a first time for everything...

**Comment by DrimTim2020** [comment]
> "I've never been wrong, everything I said was true."
> :D, there's a first time for everything...
Maybe you have it.
I have no !
In order to understand, you need to study the history of Ukraine and where two languages ​​such as Russian and Ukrainian came from.
These two languages ​​originated in the same Ukraine. According to history, there was once Kievan Rus, then the Russian language was born, at the moment Kyiv is Ukraine.
Both Russian and Ukrainian are both languages ​​that are and will always be.
Learn history, mate.
From the fact that you can do something, but do not want or do not want, this is your right.
I reported the errors that are in the package, you don’t want to fix it, I don’t give a damn about it either, I just repacked it for myself, and now I have it in Russian as it should, and I can also switch it to Ukrainian.

**Comment by DrimTim2020** [comment]
> "I've never been wrong, everything I said was true." :D, there's a first time for everything...

Maybe you have it.
I have no !
In order to understand, you need to study the history of Ukraine and where two languages ​​such as Russian and Ukrainian came from.
These two languages ​​originated in the same Ukraine. According to history, there was once Kievan Rus, then the Russian language was born, at the moment Kyiv is Ukraine.
Both Russian and Ukrainian are both languages ​​that are and will always be.
Learn history, mate.
From the fact that you can do something, but do not want or do not want, this is your right.
I reported the errors that are in the package, you don’t want to fix it, I don’t give a damn about it either, I just repacked it for myself, and now I have it in Russian as it should, and I can also switch it to Ukrainian.

**Comment by iavael** [comment]
@drogga 
1. Russian and Ukranian languages are different languages with same roots.
Russian-speakers will not understand Ukrainian (at least without significant effort and lots of mistakes).
2. Even if you want to punish russian citizens, remember that only half of people with native or second Russian actually live in Russia (around 130 mil of 260 mil). There are many people who live in exUSSR (Kazakhstan, Armenia, Georgia, Belarus, Uzbekistan etc), Europe, USA, Israel and other parts of world and who will not understand Ukranian (also there are many people in Ukraine who prefers Russian language and speak Ukranian badly). So Ukranian cannot substitute Russian for users, as I said earlier these are different languages.
3. About locales: ru_RU is Russian language in Russia, ru_UA is Russian language in Ukraine, uk_UA is Ukranian language in Ukraine.

**Comment by DrimTim2020** [comment]
> 1. Russian and Ukranian languages are different languages with same roots.
>    Russian-speakers will not understand Ukrainian (at least without significant effort and lots of mistakes).
> 2. Even if you want to punish russian citizens, remember that only half of people with native or second Russian actually live in Russia (around 130 mil of 260 mil). There are many people who live in exUSSR (Kazakhstan, Armenia, Georgia, Belarus, Uzbekistan etc), Europe, USA, Israel and other parts of world and who will not understand Ukranian (also there are many people in Ukraine who prefers Russian language and speak Ukranian badly). So Ukranian cannot substitute Russian for users, as I said earlier these are different languages.
> 3. About locales: ru_RU is Russian language in Russia, ru_UA is Russian language in Ukraine, uk_UA is Ukranian language in Ukraine.

Yes, you stated everything correctly, but you didn’t understand, no one refused the language, it’s just the wildest mistake in the package)).
They just had to delete the ru-rRU folder from the application.
And in the place of this folder there is a folder with ru-rUA in it there is a Russian language.
And since the ru-rRU folder contains the string.txt file in English, the system still thinks that the main folder is ru-rRU .
And the application is in English without translation.
I have outlined everything in detail above that you just need to delete, exclude the ru-rRU folder from the application, and then everything will work correctly.
To which I received a bunch of not pontnaya unnecessary scribbling.

**Comment by Sash0k** [comment]
@DrimTim2020 у вас из Украины есть доступ к rustore?
есть мысль форкнуть и выложить туда, ибо вещь нужная, но афтар немного того
