### ISSUE TITLE
App icon shifts after choosing "Create shortcut" and "Add to home screen"

### ISSUE THREAD

**Issue by jointfull** [butzist/ActivityLauncher#174]
When selecting an application from the list (long press or by choosing ⋮), then choosing "Create shortcut", then clicking the "Add to home screen" - make the icon of the app in your Activiry Launcher app appear in a shifted manner;
See below for "Dropbox" and "Easy Voice Recorder" icons;
This of course get reset once your app is killed and restarted.

<img src="https://user-images.githubusercontent.com/42198131/194224939-cb3a78dc-5ac8-4045-8c02-8b462004c503.jpeg" height=250>

**Comment by drogga** [comment]
Looks like an issue with large or adaptive (round) vector images _(if you can even call those "images" at this point, since they are in/as .xml of all the file types, crazy right, since when a XML files is "graphical" ?, like there's no SVG or any of the other hundreds of types...)_.

**Comment by drogga** [comment]
Looks like an issue with large or adaptive (round) vector images _(if you can even call those "images" at this point, since they are in/as .xml of all the file types, crazy right, since when a XML files is "graphical" ?, like there's no SVG which is "technically" a xml, or any of the other hundreds of types...)_.

**Comment by Mymicrog** [comment]
Fix#174

**Comment by butzist** [comment]
Still present in v2? Reopen if it's not fixed
