### ISSUE TITLE
App crashes when I want to create shortcut - Simple Bitcoin Widget version 6.8.3

### ISSUE THREAD

**Issue by chrisbarth01** [butzist/ActivityLauncher#18]
#### Expected behavior 
I expected a shortcut to the widget app I selected to be created when I clicked on 'create shortcut'

---

#### Actual behavior 
When I try to create a shortcut to a widget app, the app crashes. 

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Please note that the crash occurs when I'm creating the shortcut to a widget app. Therefore, you need a widget app (you can download one to reproduce the bug).
- Try adding a shortcut to any of your widget apps (not to the widget app's feature). A shortcut to the app itself. 
- Observe the bug.

---

Device: Gionee f100s 
Android version: v6.0
App version: v6.8.3

---

#### Recording of the bug
- https://youtu.be/EJ32IZdU18c

---

**Comment by butzist** [comment]
Hey @chrisbarth01,

seems like you are trying to create a shortcut for a package instead of a particular activity, right?

In this line we are probably getting a null pointer:
https://github.com/butzist/ActivityLauncher/blob/master/ActivityLauncherApp/src/main/java/org/thirdparty/LauncherIconCreator.java#L60

Maybe the package does not define a default activity?
