### ISSUE TITLE
labs

### ISSUE THREAD

**Issue by Ameer-101** [butzist/ActivityLauncher#191]
Hello, I have a problem. Can you help me to solve this problem?

https://user-images.githubusercontent.com/117491344/213695031-8a4054bd-2c37-44e0-87ff-c101d6c10497.mp4

**Comment by drogga** [comment]
So I knew this was coming, because of Jimmy Is Promo...
This is obviously not A.L.'s problem\issue, you must be blind or very d**b to not see it, it's Samsung's firmware problem that it loops the menu over and over.

**Comment by Ameer-101** [comment]
What is the solution

**Comment by drogga** [comment]
There's no solution (maybe try using English characters in\as "Phone number"), also it's not the place to ask questions regarding your device and OS, contact Samsung insted !

**Comment by drogga** [comment]
@butzist Can you assign a moderator to\of the comments (reviews) in PlayStore ?, IDK if it's possible, because I see at least 2 recent ones that are useless as this "issue" ticket here and should be straight up deleted. I saw them even tho I can't even sort them in the new useless PS site's UI\layout, if I could see all (newest on top), then there will probably be a lot more...
