### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ghost** [butzist/ActivityLauncher#24]
A simple toggle would be nice

**Comment by butzist** [comment]
Will see what I can do. Shouldn't this be a system-wide setting?

**Comment by vaimalaviya1233** [comment]
> A simple toggle would be nice
@MikelJohnson 
On this sunday (central time zone) in github it's finally coming with fully dark themed
Don't know when it's going be in play store since butzist have to do that.🤯🎉🤯

**Comment by vaimalaviya1233** [comment]
@butzist  hi there dark mode is ready so should I create pull request or what should I do ? because it fully supports androidx compatible but on lower end I had to manually create  styles to make it dark so there have been few changes to layout files. Finally Getting Dark 🕶.

**Comment by butzist** [comment]
@vaimalaviya1233 Awesome, please create a PR, and I will review on the weekend

**Comment by vaimalaviya1233** [comment]
@butzist I am newbie on github and full-time high school student so you might have idea i don’t know enough about github but i am getting use to it so and many files have been modified like 1 -2 lines in changed files almost 129 files so it may take me 2-3 hours to find each files and re-edit those 
if you want you can take look here check last commit 
[github.com/vaimalaviya1233/Dk-silencing-Adam](https://github.com/vaimalaviya1233/Dk-silencing-Adam)

**Comment by butzist** [comment]
@vaimalaviya1233  Can't find that commit you are referring to - the link does not work. Found 2 commits in your fork and created a PR for it. Can you update your matter branch with those changes you are referring to?

**Comment by vaimalaviya1233** [comment]
@butzist 
I haven't completed updating it to datkmod so I will create pr as soon as I'm done with update fork

**Comment by vaimalaviya1233** [comment]
@butzist darkmod is completed

**Comment by drogga** [comment]
@vaimalaviya1233 Adam is lazy, build a normal (non-debug) .apk of your fork if you want...
_You can create "Releases" directory and put the APK file there, since you can't simply put it in the "Releases" Tab - I think._

**Comment by vaimalaviya1233** [comment]
@drogga thanks I will try it and also try to resolve crash issue if I can 🙂

**Comment by drogga** [comment]
OK...
I also had a FC when I was looking to pick a custom icon for a shortcut, which happened like 3 times, then I tried to reproduce it manually on purpose in order to count\detect how many seconds or minutes takes before it crashes, but then it refused to crash, so no luck on that part, but I think it took ~30 seconds the first 3 times.

I saw that your fork now has a Debug Build APK [3.4 MB in file size - I haven't tested it], but can you generate a Release Build ?
https://github.com/vaimalaviya1233/ActivityLauncher/actions/workflows/android-release.yml

**Comment by vaimalaviya1233** [comment]
@drogga  i have generated and published release version 1.10.2 since its signed by me you will need to uninstall installed activity launcher and i have also added  Crashlytics of firebase to know where crash occurs but google services, you'll need google services installed for Crashlytics to work.
https://github.com/vaimalaviya1233/ActivityLauncher/releases/tag/1.10.2

**Comment by drogga** [comment]
Ok thanks, I installed the release 2MB build on friend's device, so you should've got some reports...
_Tho in future I prefer releases without firebase or any other analytics or debug info including\integrated\build-in, because this is too large already compared to the one from play, which is ~712 KB installed, but this 8.46 MB._

**Comment by drogga** [comment]
Ok thanks, I installed the release 2MB build on friend's device, so you should've got some reports...
_Tho in future I prefer releases without firebase or any other analytics or debug info including\integrated\build-in, because this is too large already compared to the one from play, which is ~712 KB (of bundle\splits), but this 8.46 MB (all invluded - universal) installed._

Also since you signed it with scheme v1, it won't install on A11, so from now on, please use v1+v2 schemes combined (not only one of them as v2 supports only 7.0+).

**Comment by drogga** [comment]
Ok thanks, I installed the release 2MB build on friend's device, so you should've got some reports...
_Tho in future I prefer releases without firebase or any other analytics or debug info including\integrated\build-in, because this is too large already compared to the one from play, which is ~712 KB (of bundle\splits for this device), but this is 8.46 MB (universal - even thi everything is included, but still...) when installed._

Also since you signed it with scheme v1, it won't install on A11, so from now on, please use v1+v2 schemes combined (not only one of them as v2 supports only 7.0+).

**Comment by vaimalaviya1233** [comment]
@drogga thanks for feedback  and I only included because I couldn't figure out where crash happened that's why I included firebase and it will not be on future builds. And thanks for crash log retrieved from firebase I will share with @butzist  and if you want you can Uninstall firebase and install normal version from google play store. Thanks again and will work fast as possible to resolve issue

To @butzist  how can I share crash logs with you ? Firebase or anyother way ?

**Comment by butzist** [comment]
Do we want dark mode as default for Android versions before 10? As far as I know only since 10 you can set light/dark as system default.

I would expect that for older versions, the app would use system default and only potentially allow the user to switch to a different theme.

Opinions?

**Comment by drogga** [comment]
Yes, let it be dark by default on everything, no need to make the app even heavier (in size), overcomplicate it with supporting different themes, switches and so on...
At least on Samsung device (OneUI) you can switch to dark system wide since Android 9 Pie, but technically you can do that even on A7 Nougat with the help of some third-party apps (not by installing themes or overlays), so the ones that support it can go dark there too.

**Comment by butzist** [comment]
Please try the beta release version 1.11 (in review now and should be available in a few days) and let me know if it fixes the issue
