### ISSUE TITLE
Missing themed icon after update to 2.0

### ISSUE THREAD

**Issue by LK024** [butzist/ActivityLauncher#247]
After updating to 2.0 the themed icon is missing

**Comment by butzist** [comment]
That means the resources configuration for the package doesn't have the current system theme applied? I don't have much experience with themes and also no app to use as a test case - could you point me to the app that you are using and what the expected results should be?

**Comment by LK024** [comment]
> That means the resources configuration for the package doesn't have the current system theme applied? I don't have much experience with themes and also no app to use as a test case - could you point me to the app that you are using and what the expected results should be?

![Screenshot_20240317-105812](https://github.com/butzist/ActivityLauncher/assets/99796580/b4929174-85e7-4a97-b6af-744dc9c9850a)

**Comment by LK024** [comment]
![Screenshot_20240317-105855](https://github.com/butzist/ActivityLauncher/assets/99796580/51fd7bd1-5b83-49d7-bd98-080390783e3e)

it should be so instead

**Comment by butzist** [comment]
Oh, you mean the app icon and not the shortcuts created with AL?

**Comment by LK024** [comment]
Yep

**Comment by butzist** [comment]
@drogga do you know what I need to change in  the manifest?

**Comment by drogga** [comment]
No idea what's with the monochrome (adaptive/vector/round) icon, but IMO that's low priority, given that at least it works for that users, where it doesn't at all for me, check the crash log in the discussion topic, might be related...

**Comment by LK024** [comment]
> No idea what's with the monochrome (adaptive/vector/round) icon, but IMO that's low priority, given that at least it works for that users, where it doesn't at all for me, check the crash log in the discussion topic, might be related...

I don't know what the cause is, I reported it because until the last version it worked so I thought it was easy to solve

**Comment by drogga** [comment]
By last version, you mean 1.15.2 right ?, to make it clear for the record.

**Comment by LK024** [comment]
the one just earlier at 2.0

**Comment by drogga** [comment]
Do you mean an earlier actions build here in GH ?

**Comment by LK024** [comment]
the previous one on the Play Store, It was this morning from the Play Store

**Comment by LK024** [comment]
> By last version, you mean 1.15.2 right ?, to make it clear for the record.

ok yes, it was 1.15.2

**Comment by drogga** [comment]
I guess you joined the Beta and I didn't know it was pushed there, because I don't use PS and apparently we miss communication and it's not my fault..., Leave it for now if it's bothering you, 1.15.2 should be installed instead, because this v2.0.0 is not stable and unfortunately I can't recommend it.

_Disclaimer: I prefer the good old normal with custom shape icons, which I can actually differentiate more easily, than the modern round ones, which are basically all the same to me (most with pointless white or any other color surrounding the actual real icon, juat to fit the circular space, which is ugly IMO) and I don't like the monochrome ones at all, never used it, nor I have a launcher that supports them and I don't even know how to make appear like this, also I don't intend in playing with this any time soon or at all._

**Comment by LK024** [comment]
Ah ok, yes, I'm in the beta l In fact  (I prefer round icons (naturally without empty edges) and I love theme icons, we are the two opposites😁)

**Comment by drogga** [comment]
So you also don't like how MT Manager's icon shows up, with empty unused space with a solid color ?

**Comment by LK024** [comment]
that of mt manager is fine, I hate those with the white circle around, those are really horrible

**Comment by drogga** [comment]
Any example of a good and bad one fro your screenshot(s) ?

**Comment by LK024** [comment]
> Any example of a good and bad one from your screenshot(s) ?

![Screenshot_20240317-194436](https://github.com/butzist/ActivityLauncher/assets/99796580/2f53a4e7-abbc-4872-988e-15a88db0ea06)
Prime video good, Cinema very bad (the normal version of Prime Video is the same, but it is blue)

**Comment by drogga** [comment]
"Cinema" > I agree = very bad, at least you can change it if you want with anything on a system level with a custom icon (also changes it in the app drawer) or by creating a shortcut of it, picking an icon while doing so (home screen only). I won't even suggested modding the app, because it doesn't worth it.

**Comment by butzist** [comment]
@LK024 I will try to find out what changed from 1.15.2 - might take a few weeks though. You can leave the beta program, if you prefer the old version for now.

@drogga The issue with missing Recycler component, that you are referring to, was fixed a while ago

**Comment by LK024** [comment]
> "Cinema" > I agree = very bad, at least you can change it if you want with anything on a system level with a custom icon (also changes it in the app drawer) or by creating a shortcut of it, picking an icon while doing so (home screen only). I won't even suggested modding the app, because it doesn't worth it.

Actually not really, if I make a shortcut I have the shortcut conona at the bottom right, I can want to use an icon pack thanks to the Pinned shortcuts app (create apps that are nothing but shortcut to the selected app, bit this it involves having the same app 2 times in the launcher, but in this case not even this is fine because no icon pack supports that app (being there only in Italy), and the Pinned Shortcuts app (which by the way is no longer even available on the Play Store for those who have not already downloaded it in the past) Allows only or to change icon packs or add a self-generated themed icon to apps that don't have it, but not to put a custom icon

**Comment by LK024** [comment]
> @LK024 I will try to find out what changed from 1.15.2 - might take a few weeks though. You can leave the beta program, if you prefer the old version for now.
> 
> @drogga The issue with missing Recycler component, that you are referring to, was fixed a while ago

Yes, I just did it, I will keep an eye on the GitHub so as soon as I read that it is resolved I return to beta (yes I am obsessive to always have the latest version of everything hahaha😁😅)

**Comment by drogga** [comment]
@butzist - I've replied in the discussion, regarding the recycler, let's continue this one there.

@LK024 - Latest version doesn't mean a better version, putting bugs on side, some devs. do sometimes remove features, whether forced to, being greedy or something else.
I wouldn't suggest the icon replacement without even playing around myself in the past (years ago), IDK if that's still the case, but Activity Launcher can create a shortcut with a custom icon, if not this one, then I think the Activity Manager by sdex allows picking one from the storage and you can have 1 or more of the same shortcut on the home screen and place it in a folder, but a tiny icon of the app that created it will show up on it, there's now way around it, unless it's actually a widget (nothing to do with the App Drawer) and users used to be able to change the ones in the app drawer as well, by using a custom icon pack, either created by themselves (Samsung thing ?) or by someone else (say from PS) and going to that sophisticated icon pack app and picking which apps icons to change and if not available one in the packages/pack for a particular app, allowing to forcefully create and replace such. I haven't played that much with this so I won't argue if it's still applicable, nor I remember which Icon Packs I used, but I know it worked in the past, since then there were a lot of limitations/restrictions forced by Google, so IDK and I won't be playing with this again, simply because I'm not a fan.

**Comment by LK024** [comment]
@drogga in fact from android 14 no they can never make shortcuts without the logo at the bottom right (for example watch Next DNS) Actually on Pixel Launcher if you put a shortcut, backup, format the phone and then restore the backup the shortcuts you put them back without any logo (if it is shortcut to a system app  (type file that is not accessible is a shortcut made last year before formatting when I exited the beta of android 14 (it had broken my assistant💀)) or done through a system app ) 
![Screenshot_20240317-100701](https://github.com/butzist/ActivityLauncher/assets/99796580/30333beb-f56e-4eb7-aa09-3643b747b301)

**Comment by drogga** [comment]
Nova Launcher can replace icons, too bad it was ruined, not that it was ever perfect - I had issues by using a BT mouse on a device and N.L. expected a touch action {finger} instead of a mouse cursor, so certain actions were not being executed, because of the stupidity of the devs. failing to do a decent coding and because they didn't care about user's feedback, so I ditched it and don't use any third-party launchers, just stock Samsung's, the Pixel one is not one of the good ones tho.

**Comment by LK024** [comment]
Actually excluding this limit for shortcuts I love the Pixel Launcher, but it is subjective of course👍

**Comment by butzist** [comment]
@LK024 please try https://github.com/butzist/ActivityLauncher/releases/tag/2.0.1 - it adds a possibly missing monochrome color on the round icon.
