### ISSUE TITLE
Some icons are outdated

### ISSUE THREAD

**Issue by MikelJohnson** [butzist/ActivityLauncher#25]
Such as:
- search ([for reference](https://material.io/resources/icons/?icon=search&style=baseline))
- drop down ([reference 1](https://material.io/resources/icons/?icon=arrow_drop_down&style=baseline) and [2](https://material.io/components/menus/#dropdown-menu))

You should use Material icons

**Comment by butzist** [comment]
How can I update them?

**Comment by vaimalaviya1233** [comment]
@butzist 
I will try to implement and try to make it able to change it between day and dark mode since i cannot  find way to make old menu chnge to dark theme and i think create pull request

(i am still getting use to github so correct me if that’s not the correct way to contribute to this project)

adn if you want to get some idea here is the [Link](https://material.io/components/menus/android#using-menus)

**Comment by vaimalaviya1233** [comment]
@MikelJohnson 
Update for updated icons and menu will be ready in next few days 👍🏼

**Comment by vaimalaviya1233** [comment]
Icons are up-to-date
