### ISSUE TITLE
Launcher Unable to "launch" Root Access Permitted

### ISSUE THREAD

**Issue by Oneofakind77** [butzist/ActivityLauncher#293]
Essentially like the title states. I am unable to get activities to launch even after giving root access to the app. It's just giving me an error message and saying my permission has been denied. 

Could you explain to me what I can do to fix this issue 
I'm not super tech savvy. Though I'm a fast learner but I don't have a whole lot of knowledge as of right now. 

Meaning, that I thought all I needed to do was give root access. However, the app is behaving as if I need to give some other permission and I don't know how to go about doing that. 
If you could get back to me, at your earliest convenience, I would greatly appreciate it! 

I've included screenshots of what I was intending to run and showing that I have given root access permission.
![Screenshot_20240814_121443_Activity Launcher](https://github.com/user-attachments/assets/af7b110d-807e-495c-aa81-22cb23b47f5c)
![Screenshot_20240814_121451_Activity Launcher](https://github.com/user-attachments/assets/fc280a9b-1686-4495-94df-22dbe5efb40f)

Thanks, in advance, for your prompt attention to this matter!
Regards,
Christine M.

**Comment by Oneofakind77** [comment]
How can I get someone to pay attention to this or get back to me somehow? 
I'm not exactly psyched about having to do things this way. 
I downloaded this app from the PlayStore. I should be able to contact the developer via a link in PlayStore. Like you can with every other app. But instead they bring me here and I'm not a developer and I don't know what all of your technical jargon means. 
What I do know is THIS APP ISN'T WORKING FOR SHIT!
I've given it root access and it will not let me run any of these activities as root. So what the fuck? I really wish someone would get back to me!!!!

**Comment by drogga** [comment]
Watch your language.
You didn't mention a single detail about your device, like Brand, Model, OS ver., custom ROM or not, Root method, or the app ver. you are running, I can see that this is an old ver., we are now at 2.x (Beta on PS, tho the .apk is available on F-Droid) and there's a separate button/menu entry for launching activities with Root, I guess you aren't using that one, because for me on A.8 it works (I don't have anything Rooted with newer OS ver.).

**Comment by drogga** [comment]
@Oneofakind77 Watch your language.

You didn't mention a single detail about your device, like Brand, Model, OS ver., custom ROM or not, Root method, or the app ver. you are running, I can see that this is an old ver., we are now at 2.x (Beta on PS, tho the .apk is available on F-Droid) and there's a separate button/long press context menu entry in v.1.x for launching activities with Root, I guess you aren't using that one, because for me on A.8 it works (I don't have anything Rooted with newer OS ver.).

Oh and btw - don't think/assume that every activity will launch, just because there's root, some are not exported for a reason and either nothing will happen or the app will crash.
