### ISSUE TITLE
Cannot shortcut - Developer Options / Running Services

### ISSUE THREAD

**Issue by xa4hf8** [butzist/ActivityLauncher#339]
Shortcut displays a list of “All apps” instead of Running Services

**Comment by drogga** [comment]
Blame Google.

**Comment by xa4hf8** [comment]
I created a shortcut to `Developer Options` instead, and now an error message is presented:

`java.lang.SecurityException: Permission Denial`

— is this the same issue that #278 was intended to address?

**Comment by drogga** [comment]
IDK, on A.8.1 x86 live boot, even with root and also playing with the unexported activities there doesn't seems to be a way to directly launch that menu (anymore and I doubt that anything changed for better even in A.16), all seem part of the SubSettings activity, I've read that an app called **Dev Tools Pro** can probably somehow launch this or it lists them inside it, like others do, but I haven't tested it.

If you don't have root and still want to play around and check for yourself, you can probably use either **Root Activity Launcher** by Zacharee (source available on GH, but otherwise the app is Paid on/in PS, tho you can probably try build it or find an .apk online) or **App Manager** by Muntashir Akon, the first uses Shizuku, the second uses its own authorizers, both use a trick thanks to google assistant to launch them.
