### ISSUE TITLE
I can't turn on 120hz on samsung galaxy s10+

### ISSUE THREAD

**Issue by Pietepost** [butzist/ActivityLauncher#54]
I can't turn on 120hz with my samsung galaxy s10+ and i have a 120hz display and i have developer mode on and 
I set my screen resolution is set to the lowest it can in the 
Settings! Please help me.

**Comment by vaimalaviya1233** [comment]
Need More information

1. are you installing through android studio Or from any stores(google play, f-droid)?
2. is app crashing(closes app right after you opned)?

**Comment by drogga** [comment]
@Pietepost why lied to you that SGS10+ supports high refresh rate ?, cuz is not true !
You can search for "motion" and maybe even set it to "high" \ 120Hz (placebo), but it won't work as it's not actually supported by the display\screen hardware tech itself, its not something you can change on software bases.
Samsung devs. left it there, simply because they are lazy and don't want to bother changing roms\firmwares for all the different models they make too much, hiding, disabling activities or making them "private".

Also this "issue" has nothing to do with this app's code at all, so all other topics like this one should be closed and even deleted if it's possible !

**Comment by vaimalaviya1233** [comment]
@drogga 
@Pietepost 
If that's the case this issue should be closed
because turning on 120hz refresh rate is not what this launcher's problem @Pietepost  should be contacting samsung right now
THIS IS NOT SAMSUNG'S CONTACT WEBSITE
PLEASE AND KINDLY CLOSE THIS ISSUE
