### ISSUE TITLE
Creating shortcut

### ISSUE THREAD

**Issue by megamanxzlol** [butzist/ActivityLauncher#55]
I cant't find my way into creating a shortcut, everytime I try it sais that it was created but I cant find it anywhere, am I doing something wrong? Using xiaomi poco x3 version 12.0.7

**Comment by drogga** [comment]
@megamanxzlol Can other similar apps create shortcuts to your home screen, if not, then the fault is in the Xiaomi\Poco launcher itself, basically nothing can be done, as there are no more shortcut permissions that can be added...
If you use a custom launcher diffrent from the POCO's one, then check the stock one, it's probably there instead of the custom's.

**Comment by megamanxzlol** [comment]
Thanks, I suspected it was  xiaomi's problem, I'm actually using stock
launcher. This wouldn't be the only problem with xiaomi. Anyways, thanks
again

**Comment by vaimalaviya1233** [comment]
@megamanxzlol 
Please Kindly Close this issue if it's been solved 😳
