### ISSUE TITLE
60hz to 120hz 

### ISSUE THREAD

**Issue by HUSNAIN4443** [butzist/ActivityLauncher#57]

**Comment by drogga** [comment]
Who told\lied to you that SG S\N 20 supports high refresh rate ?, cuz is not true !
You can search for "motion" and maybe even set it to "high" \ 120Hz (placebo), but it won't work as it's not actually supported by the display\screen hardware tech itself, its not something you can change on software bases.
Samsung devs. left it there, simply because they are lazy and don't want to bother changing roms\firmwares for all the different models they make too much, hiding, disabling activities or making them "private".

Also this "issue" has nothing to do with this app's code at all, so all other topics like this one should be closed and even deleted if it's possible !

Owner: You can grant me permission to close (pointless) issues like this one and add labels (tags) when is necessary - if you want...

**Comment by HUSNAIN4443** [comment]
Thanks for informing me about it that its not that app its the problem the
the mobile display..
I'm sorry 😞 for that because I'm was thinking that the app is not working
but you told me the real story.  Thank you so much.  If you want to delete
that issue you can

**Comment by gamingfield** [comment]
and the galaxy note 8
have 120Hz?

**Comment by drogga** [comment]
@gamingfield **NO, only 2020>^ S & Note models/series, nothing before that !**
...I don't get what is ho hard for you to understand..., did you see on any of those 120Hz in the specs, let's say in GsmArena > No !, so why do you thing that you are exception and samsung put by mistake a high refresh screen specifically in your device, but not in others of the same huh ?

@HUSNAIN4443 Please close this issue, you should be able, cuz I can't and it seems that there's no one else around that can.
Thanks.

**Comment by drogga** [comment]
@gamingfield - **NO, only 2020>^ S & Note models/series, nothing before that !**
...I don't get why is so hard for you to understand..., did you see on any of those 120Hz in the specs, let's say in GsmArena > No !, so why do you thing that you are exception and samsung put by mistake a high refresh screen specifically in your device, but not in others of the same huh ?

@HUSNAIN4443 Please close this issue, you should be able, cuz I can't and it seems that there's no one else around that can.
Thanks.

**Comment by HUSNAIN4443** [comment]
Its solved outside

**Comment by drogga** [comment]
Ok, thanks, but you didn't have to edit your OP to nothing...
