### ISSUE TITLE
Not working on redmi 8 

### ISSUE THREAD

**Issue by Abbaful** [butzist/ActivityLauncher#59]
Please fixed this issue on this app not working on redmi 8

**Comment by drogga** [comment]
@Abbaful - What exactly isn't working ?
...if tou mean that you can't create shortcuts to the home screen, then you need to go to "Other permissions" and specifically allow that, I actually explained it better in one of the closed "issues" (tickets) recently, but if this is not the problem, then please provide some more info, like Android Version, LogCat (if possible), screenshot or screen record if the crash or whatever... anything useful actually, cuz claiming only that isn't working is not helpful to anyone, because this isn't a known issue or something !

**Comment by Abbaful** [comment]
The problem is that, I cannot clear cache under storage

**Comment by Abbaful** [comment]
I can't clear cache on redmi 8 under storage settings

**Comment by drogga** [comment]
**Not the apps's fault !!!**
@butzist please close this, or you can give me a permission to be able close them...

**Comment by drogga** [comment]
@Abbaful
**Not the apps's fault !!!**
...IDK why ppl keep opening pointless issues\tickets like this one...

@butzist - please close this, ...or you can give me a permission to be able close them...
