### ISSUE TITLE
Shortcut is not working in Realme X2 cn

### ISSUE THREAD

**Issue by SakhawatAkib** [butzist/ActivityLauncher#63]
![Screenshot_2021-02-11-14-14-33-08](https://user-images.githubusercontent.com/47961016/107614838-459fb500-6c75-11eb-9fd4-04ee33231cef.jpg)
I create a shortcut for settings -> pickUpRegion
But that shortcut failed to open like attached picture

**Comment by drogga** [comment]
Allow all the app's permissions (especially the extra ones that those Chinese manufacturers use - under "Other Permissions") and try again.
You can also try with a competitor\similar app or creating a shortcut to AL itself from within the app and see if this will work, because nobody can guess what the issue might be, when not everyone uses such crappy devices that put super unnecessary restrictions and make idiotic decisions for their custom forks of android.

**Comment by drogga** [comment]
...report back how it went...
Also please close this issue ticket if you solve the problem, which again - is probably not the app's fault, thanks.

**Comment by Morph21** [comment]
I'm not sure how it went for @SakhawatAkib but changing permission solved the issue for me on Redmi note 7 (miui 12)
