### ISSUE TITLE
Android TV "Error creating shortcut"

### ISSUE THREAD

**Issue by brentonv** [butzist/ActivityLauncher#64]
I get this [error](https://i.ibb.co/j5bDhgt/Pin-Shortcut.png) when trying to create a shortcut on Android TV.

> **Error creating shortcut**
> Current launcher does not support "PinShortcut". Unable to create shortcut

Could you please add an option in context menu to create Android TV shortcut.

Thanks for all the work you put into this project.

**Comment by drogga** [comment]
Not possible, simply because the leanback launcher doesn't support shortcuts at all (nor the other third party TV launchers), it uses banners instead, which should be pre-build by the app developer.

https://play.google.com/store/apps/details?id=by4a.sideloaded_app_icons
This paid app claims that it can create ones, but I never tried it, so if you purchase\buy it, please backup and send me the .apk if you can. Thanks in advance ;)

AppCloner can also be used for this, but I don't recommend it...

If you want to create shortcuts just like you do on a Phone or Tablet, then install a custom launcher for thise, like Nova, Apex or whichever else that is not designed to be used on TV.

Anyway, please close this ticket\issue, simply because it's not the app's fault and it has nothing to do with your problem.

**Comment by brentonv** [comment]
Thanks for your response @drogga but I will rather hear from Adam about what he has to say and then he can close the issue. I am certainly not interested in purchasing an app for you, but you could use this for free if you want to create Android TV shortcuts that you claim is not possible https://atvlauncher.trekgonewild.de

**Comment by drogga** [comment]
Yeah, you can wait for Adam's response as much as you want...!
You got it all wrong, I gave you a damn suggestion of a good and friendly will, I didn't tell you to purchase any app for me or anyone else, honestly I don't know where the heck you read those stuff and why I'm wasting my time in vain because of stupid ppl...

This online tool creates a separate app that launches the main activity of the target one as a banner, not a shortcut, as I already explained, obviously you don't know what you are talking about or want and don't make any difference between the two, so good luck !
