### ISSUE TITLE
Running Activities on secondary screen.?

### ISSUE THREAD

**Issue by focus17** [butzist/ActivityLauncher#65]
I have my hands on a new LG Wing and trying to use a necent gamepad on the secondary screen. 
Online everyone has been trying to get the LG Gamepad Service to run the "Swivel Screen" with your app but as for as far as I can find, with no success.

Are you familiar with if and how I would be able to run a service application on an alternate display?

**Comment by drogga** [comment]
I don't think it's possible or related to (or has anything to do with) this app, simply because in split mode a custom LG launcher is being used which uses banners instead of regular icons\shortcuts, but maybe you can map some key to launch it with a Key Mapper app...

This issue should\can be closed as it's not the project's \ app's fault !
