### ISSUE TITLE
Runtime Exception on AllTasksListAdapter.java due to Package manager has died

### ISSUE THREAD

**Issue by vaimalaviya1233** [butzist/ActivityLauncher#66]
crash logs retrieved from firebase with help of @drogga 

![Web capture_15-3-2021_20338_console firebase google com](https://user-images.githubusercontent.com/55515799/111240605-920a4780-85c9-11eb-8f4f-c4609bd0f367.jpeg)

**Comment by vaimalaviya1233** [comment]
Although I do not have experience in kotlin but I have doubt if it solves crash issue if tested locally by converting to kotlin ?

**Comment by vaimalaviya1233** [comment]
Alright we need some improvements here because this happened reason is that RAM was too low and Android OS likes to reserve some RAM for it's operation process and this makes issue because installed applications are more this requires more RAM(memory)
month ago before I did factory reset I had like 5300+ application installed and at that time i seen memory usage of activity launcher(1.10.0) it was around 950 MB to 1 GB because it gets all activities of all apps installed but it didn't crash since I got 12GB RAM so even if we minimize memory usage it would not help since **we need memory based on how many apps are installed. and RAM is Limited by hardware specifics** 

## Solution

**memory usage improvements needed**

**_memory usage can be minimized by closing background processes which other apps runs alternatively we can enable developer mode  and go down to apps section(might be different than mine though) and turn on don't keep activities option which it self-explains it can kill important activities like music. but except that if you don't want that then choose option below which is Background process limit_**

otherwise if found another way refer here  or get phone with high RAM which I personally don't like neither anyone else

**Comment by drogga** [comment]
Your release build with firebase eats 87MB of RAM here, it's not how I'd like it to be, but it's not that much either, still a lot tho...

**Comment by vaimalaviya1233** [comment]
like i said before there was no means of mine to collect any data except crash log and since it's done you can uninstall it and i have released 1.10.5  lighter version(original with theme)
and it's 258 KB so hopefully it might not crash(can't tell for sure) since i removed firebase from it and any other things that could take up storage

**Comment by drogga** [comment]
PLEASE **Learn to read** for god's sake...
You wrote that you think that the crashes are because it sucks a lot of memmory on your device (~1 GB), I simply replied how much RAM it takes of on my end, nothing more and I definately didn't complained that you collect any data besides the crash logs... so the problem ain't that cheif.

So you basically have put absolutely the same thing as on Play Store, nothing fixed - still crashes and it's with the original white theme for me... what's the point...?

BTW - When you release a new version and bump\increase the version code (aka. name), also bump\increase the build ver. code, don't lower it down, because it won't update over the previous build (when signature is the same), just because the build number is lower.

**Comment by drogga** [comment]
#24
